### ISSUE TITLE
Any possibility of IE11 support?

### ISSUE THREAD

**Issue by artem-v-shamsutdinov** [slmgc/Nothing#6]
Hi,

Love the library, could save ton of code and bugs and make code more readable!  We would like to use it in production but we have to support IE11 for the next 4+ years.   I've tried to polyfill both Symbol and Proxy with:

https://github.com/zloirock/core-js
https://github.com/GoogleChrome/proxy-polyfill

respectively.  The "Nothing" object does get initialized but ends up having no effect:

```ts
import 'core-js/es6/symbol';
import 'proxy-polyfill/proxy.min.js';
import {Nothing} from "nothing-mock";

const test = Nothing;
console.log(test.a.b.c());
```

Error:
```
Unable to get property 'b' of undefined or null reference
```
Any chance of adding IE11 support?

Thanks, :)

**Comment by slmgc** [comment]
Hi,

Sadly, there is no way to polyfill Proxy properly and add support for old browsers such as IE11. I guess the only option for you is to use [optional chaining](https://www.npmjs.com/package/babel-plugin-transform-optional-chaining) in case you have a transpilation step.

Hope this helps!
